# chirpy theme demo
lang: en
timezone: America/New_York

theme: jekyll-theme-chirpy

# Site settings
title: Your Name
tagline: Your Awesome Tagline
description: >- 
  Your site description for SEO and social sharing.
url: 'https://yourusername.github.io'

# Personal details
avatar: /assets/img/avatar.jpg  # Add your photo to assets/img/

social:
  name: Your Name
  email: your.email@example.com
  links:
    - https://github.com/yourusername
    - https://twitter.com/yourhandle
    - https://linkedin.com/in/yourprofile
    # Add other social links as needed

# Chirpy specific settings
twitter:
  username: yourhandle

github:
  username: yourusername

theme_mode: auto  # auto, light, dark - auto switches based on system preference

# Comments (choose one)
comments:
  active: disqus  # or giscus, utterances
  disqus:
    shortname: your-disqus-shortname
  # OR
  giscus:
    repo: username/repo
    repo-id: XXX
    category: Announcements
    category-id: XXX

# Analytics
google_analytics:
  id: G-XXXXXXXXXX  # Your Google Analytics ID

# SEO and performance
paginator:
  per_page: 10